trigger:
  branches:
    include:
    - '*'

pool:
  name: TBS Linux Self Hosted

steps:
- script: |
    echo Sync azure repo
    B64_PAT=$(echo -n ":$PAT" | base64)
    git push https://$PAT@dev.azure.com/tbs-sct/GCExchange/_git/$REPO_NAME --all
    cd Sync_directory
    git remote add --mirror=fetch upstream https://github.com/gcxchange-gcechange/$REPO_NAME
    git fetch upstream --tags
    git -c http.extraHeader="Authorization: Basic ${B64_PAT}" push origin --all
  env:
    PAT: $(PAT)
    REPO_NAME: "appsvc-function-dev-cm-sche-dotnet001"
  displayName: 'Sync repo'
